---
abstract: 'Digi-ID implementation'
author:
  - 'Michael Vu <email@michael.vu>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.014, CPAN::Meta::Converter version 2.150010'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DigiByte-DigiID
requires:
  Crypt::OpenPGP::Digest: '0'
  Crypt::OpenSSL::Random: '0'
  Crypto::ECC: '0'
  Data::UUID: '0'
  Digest::SHA: '0'
  JSON::XS: '0'
  MIME::Base64: '0'
  Math::BigInt: '1.999818'
  Math::BigInt::GMP: '1.6007'
  String::Pad: '0'
  URI::Escape: '0'
version: '0.004'
x_generated_by_perl: v5.30.2
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: MIT
